// lib/geografia.ts — División Territorial RD (ONE 2019) — orden alfabético
export interface Municipio { codigo: string; nombre: string }
export interface Provincia  { codigo: string; nombre: string; municipios: Municipio[] }

export const PROVINCIAS: Provincia[] = [
  { codigo: '02', nombre: 'Azua', municipios: [
    { codigo: '02-01', nombre: 'Azua' },
    { codigo: '02-10', nombre: 'Estebanía' },
    { codigo: '02-09', nombre: 'Guayabal' },
    { codigo: '02-02', nombre: 'Las Charcas' },
    { codigo: '02-03', nombre: 'Las Yayas de Viajama' },
    { codigo: '02-04', nombre: 'Padre Las Casas' },
    { codigo: '02-05', nombre: 'Peralta' },
    { codigo: '02-07', nombre: 'Pueblo Viejo' },
    { codigo: '02-06', nombre: 'Sabana Yegua' },
    { codigo: '02-08', nombre: 'Tábara Arriba' },
  ]},
  { codigo: '03', nombre: 'Baoruco', municipios: [
    { codigo: '03-02', nombre: 'Galván' },
    { codigo: '03-05', nombre: 'Los Ríos' },
    { codigo: '03-01', nombre: 'Neiba' },
    { codigo: '03-03', nombre: 'Tamayo' },
    { codigo: '03-04', nombre: 'Villa Jaragua' },
  ]},
  { codigo: '04', nombre: 'Barahona', municipios: [
    { codigo: '04-01', nombre: 'Barahona' },
    { codigo: '04-02', nombre: 'Cabral' },
    { codigo: '04-06', nombre: 'El Peñón' },
    { codigo: '04-03', nombre: 'Enriquillo' },
    { codigo: '04-08', nombre: 'Fundación' },
    { codigo: '04-11', nombre: 'Jaquimeyes' },
    { codigo: '04-07', nombre: 'La Ciénaga' },
    { codigo: '04-09', nombre: 'Las Salinas' },
    { codigo: '04-04', nombre: 'Paraíso' },
    { codigo: '04-10', nombre: 'Polo' },
    { codigo: '04-05', nombre: 'Vicente Noble' },
  ]},
  { codigo: '05', nombre: 'Dajabón', municipios: [
    { codigo: '05-01', nombre: 'Dajabón' },
    { codigo: '05-05', nombre: 'El Pino' },
    { codigo: '05-02', nombre: 'Loma de Cabrera' },
    { codigo: '05-03', nombre: 'Partido' },
    { codigo: '05-04', nombre: 'Restauración' },
  ]},
  { codigo: '01', nombre: 'Distrito Nacional', municipios: [
    { codigo: '01-01', nombre: 'Santo Domingo de Guzmán' },
  ]},
  { codigo: '06', nombre: 'Duarte', municipios: [
    { codigo: '06-02', nombre: 'Arenoso' },
    { codigo: '06-03', nombre: 'Castillo' },
    { codigo: '06-07', nombre: 'Eugenio María de Hostos' },
    { codigo: '06-06', nombre: 'Las Guaranas' },
    { codigo: '06-04', nombre: 'Pimentel' },
    { codigo: '06-01', nombre: 'San Francisco de Macorís' },
    { codigo: '06-05', nombre: 'Villa Riva' },
  ]},
  { codigo: '08', nombre: 'El Seibo', municipios: [
    { codigo: '08-01', nombre: 'El Seibo' },
    { codigo: '08-02', nombre: 'Miches' },
  ]},
  { codigo: '07', nombre: 'Elías Piña', municipios: [
    { codigo: '07-02', nombre: 'Bánica' },
    { codigo: '07-01', nombre: 'Comendador' },
    { codigo: '07-03', nombre: 'El Llano' },
    { codigo: '07-04', nombre: 'Hondo Valle' },
    { codigo: '07-06', nombre: 'Juan Santiago' },
    { codigo: '07-05', nombre: 'Pedro Santana' },
  ]},
  { codigo: '09', nombre: 'Espaillat', municipios: [
    { codigo: '09-02', nombre: 'Cayetano Germosén' },
    { codigo: '09-03', nombre: 'Gaspar Hernández' },
    { codigo: '09-04', nombre: 'Jamao Al Norte' },
    { codigo: '09-01', nombre: 'Moca' },
    { codigo: '09-05', nombre: 'San Víctor' },
  ]},
  { codigo: '30', nombre: 'Hato Mayor', municipios: [
    { codigo: '30-03', nombre: 'El Valle' },
    { codigo: '30-01', nombre: 'Hato Mayor' },
    { codigo: '30-02', nombre: 'Sabana de La Mar' },
  ]},
  { codigo: '19', nombre: 'Hermanas Mirabal', municipios: [
    { codigo: '19-01', nombre: 'Salcedo' },
    { codigo: '19-02', nombre: 'Tenares' },
    { codigo: '19-03', nombre: 'Villa Tapia' },
  ]},
  { codigo: '10', nombre: 'Independencia', municipios: [
    { codigo: '10-05', nombre: 'Cristóbal' },
    { codigo: '10-02', nombre: 'Duvergé' },
    { codigo: '10-01', nombre: 'Jimaní' },
    { codigo: '10-06', nombre: 'Mella' },
    { codigo: '10-03', nombre: 'La Descubierta' },
    { codigo: '10-04', nombre: 'Postrer Río' },
  ]},
  { codigo: '11', nombre: 'La Altagracia', municipios: [
    { codigo: '11-01', nombre: 'Higüey' },
    { codigo: '11-02', nombre: 'San Rafael del Yuma' },
  ]},
  { codigo: '12', nombre: 'La Romana', municipios: [
    { codigo: '12-02', nombre: 'Guaymate' },
    { codigo: '12-01', nombre: 'La Romana' },
    { codigo: '12-03', nombre: 'Villa Hermosa' },
  ]},
  { codigo: '13', nombre: 'La Vega', municipios: [
    { codigo: '13-02', nombre: 'Constanza' },
    { codigo: '13-03', nombre: 'Jarabacoa' },
    { codigo: '13-04', nombre: 'Jima Abajo' },
    { codigo: '13-01', nombre: 'La Vega' },
  ]},
  { codigo: '14', nombre: 'María Trinidad Sánchez', municipios: [
    { codigo: '14-02', nombre: 'Cabrera' },
    { codigo: '14-03', nombre: 'El Factor' },
    { codigo: '14-01', nombre: 'Nagua' },
    { codigo: '14-04', nombre: 'Río San Juan' },
  ]},
  { codigo: '28', nombre: 'Monseñor Nouel', municipios: [
    { codigo: '28-01', nombre: 'Bonao' },
    { codigo: '28-02', nombre: 'Maimón' },
    { codigo: '28-03', nombre: 'Piedra Blanca' },
  ]},
  { codigo: '15', nombre: 'Monte Cristi', municipios: [
    { codigo: '15-02', nombre: 'Castañuelas' },
    { codigo: '15-03', nombre: 'Guayubín' },
    { codigo: '15-04', nombre: 'Las Matas de Santa Cruz' },
    { codigo: '15-01', nombre: 'Monte Cristi' },
    { codigo: '15-05', nombre: 'Pepillo Salcedo' },
    { codigo: '15-06', nombre: 'Villa Vásquez' },
  ]},
  { codigo: '29', nombre: 'Monte Plata', municipios: [
    { codigo: '29-02', nombre: 'Bayaguana' },
    { codigo: '29-01', nombre: 'Monte Plata' },
    { codigo: '29-05', nombre: 'Peralvillo' },
    { codigo: '29-03', nombre: 'Sabana Grande de Boyá' },
    { codigo: '29-04', nombre: 'Yamasá' },
  ]},
  { codigo: '16', nombre: 'Pedernales', municipios: [
    { codigo: '16-02', nombre: 'Oviedo' },
    { codigo: '16-01', nombre: 'Pedernales' },
  ]},
  { codigo: '17', nombre: 'Peravia', municipios: [
    { codigo: '17-01', nombre: 'Baní' },
    { codigo: '17-03', nombre: 'Matanzas' },
    { codigo: '17-02', nombre: 'Bánica' },
  ]},
  { codigo: '18', nombre: 'Puerto Plata', municipios: [
    { codigo: '18-02', nombre: 'Altamira' },
    { codigo: '18-03', nombre: 'Guananico' },
    { codigo: '18-05', nombre: 'Los Hidalgos' },
    { codigo: '18-06', nombre: 'Luperón' },
    { codigo: '18-04', nombre: 'Cayetano Germosén' },
    { codigo: '18-01', nombre: 'Puerto Plata' },
    { codigo: '18-07', nombre: 'Sosúa' },
    { codigo: '18-08', nombre: 'Villa Isabela' },
    { codigo: '18-09', nombre: 'Villa Montellano' },
  ]},
  { codigo: '20', nombre: 'Samaná', municipios: [
    { codigo: '20-03', nombre: 'Las Terrenas' },
    { codigo: '20-01', nombre: 'Samaná' },
    { codigo: '20-02', nombre: 'Sánchez' },
  ]},
  { codigo: '21', nombre: 'San Cristóbal', municipios: [
    { codigo: '21-03', nombre: 'Bajos de Haina' },
    { codigo: '21-04', nombre: 'Cambita Garabitos' },
    { codigo: '21-08', nombre: 'Los Cacaos                             347' },
    { codigo: '21-02', nombre: 'Sabana Grande de Palenque' },
    { codigo: '21-01', nombre: 'San Cristóbal' },
    { codigo: '21-07', nombre: 'San Gregorio de Nigua' },
    { codigo: '21-05', nombre: 'Villa Altagracia' },
    { codigo: '21-06', nombre: 'Yaguate' },
  ]},
  { codigo: '31', nombre: 'San José de Ocoa', municipios: [
    { codigo: '31-03', nombre: 'Rancho Arriba' },
    { codigo: '31-02', nombre: 'Sabana Larga' },
    { codigo: '31-01', nombre: 'San José de Ocoa' },
  ]},
  { codigo: '22', nombre: 'San Juan', municipios: [
    { codigo: '22-02', nombre: 'Bohechío' },
    { codigo: '22-03', nombre: 'El Cercado' },
    { codigo: '22-04', nombre: 'Juan de Herrera' },
    { codigo: '22-05', nombre: 'Las Matas de Farfán' },
    { codigo: '22-01', nombre: 'San Juan' },
    { codigo: '22-06', nombre: 'Vallejuelo' },
  ]},
  { codigo: '23', nombre: 'San Pedro de Macorís', municipios: [
    { codigo: '23-04', nombre: 'Consuelo' },
    { codigo: '23-06', nombre: 'Guayacanes' },
    { codigo: '23-02', nombre: 'Los Llanos' },
    { codigo: '23-05', nombre: 'Quisqueya' },
    { codigo: '23-03', nombre: 'Ramón Santana' },
    { codigo: '23-01', nombre: 'San Pedro de Macorís' },
  ]},
  { codigo: '25', nombre: 'Santiago', municipios: [
    { codigo: '25-10', nombre: 'Baitoa' },
    { codigo: '25-02', nombre: 'Bisonó' },
    { codigo: '25-03', nombre: 'Jánico' },
    { codigo: '25-04', nombre: 'Licey al Medio' },
    { codigo: '25-08', nombre: 'Puñal' },
    { codigo: '25-09', nombre: 'Sabana Iglesia' },
    { codigo: '25-05', nombre: 'San José de Las Matas' },
    { codigo: '25-01', nombre: 'Santiago' },
    { codigo: '25-06', nombre: 'Tamboril' },
    { codigo: '25-07', nombre: 'Villa González' },
  ]},
  { codigo: '26', nombre: 'Santiago Rodríguez', municipios: [
    { codigo: '26-03', nombre: 'Monción' },
    { codigo: '26-01', nombre: 'San Ignacio de Sabaneta' },
    { codigo: '26-02', nombre: 'Villa Los Almácigos' },
  ]},
  { codigo: '32', nombre: 'Santo Domingo', municipios: [
    { codigo: '32-04', nombre: 'Boca Chica' },
    { codigo: '32-06', nombre: 'Los Alcarrizos' },
    { codigo: '32-07', nombre: 'Pedro Brand' },
    { codigo: '32-05', nombre: 'San Antonio de Guerra' },
    { codigo: '32-01', nombre: 'Santo Domingo Este' },
    { codigo: '32-03', nombre: 'Santo Domingo Norte                     545' },
    { codigo: '32-02', nombre: 'Santo Domingo Oeste' },
  ]},
  { codigo: '24', nombre: 'Sánchez Ramírez', municipios: [
    { codigo: '24-02', nombre: 'Cevicos' },
    { codigo: '24-01', nombre: 'Cotuí' },
    { codigo: '24-03', nombre: 'Fantino' },
    { codigo: '24-04', nombre: 'La Mata' },
  ]},
  { codigo: '27', nombre: 'Valverde', municipios: [
    { codigo: '27-02', nombre: 'Esperanza' },
    { codigo: '27-03', nombre: 'Laguna Salada' },
    { codigo: '27-01', nombre: 'Mao' },
  ]},
]

export const getMunicipios = (cod: string) => PROVINCIAS.find(p => p.codigo === cod)?.municipios ?? []
export const getProvByNombre = (n: string) => PROVINCIAS.find(p => p.nombre === n)
export const getMuniByNombre = (pc: string, n: string) => getMunicipios(pc).find(m => m.nombre === n)
export const NOMBRES_PROVINCIAS = PROVINCIAS.map(p => p.nombre)