// lib/jce-geo-lookup.ts
// Lookup estático JCE — generado del Padrón Febrero 2024
// Permite obtener los ID numéricos requeridos por Art. 18 del Reglamento JCE 2026

export interface JCEProvincia {
  id: number
  nombre: string
}

export interface JCEMunicipio {
  id: number
  nombre: string
  idProvincia: number
}

export interface JCEDistritoMunicipal {
  id: number
  nombre: string
  idProvincia: number
  idMunicipioPadre: number
}

export const JCE_PROVINCIAS: JCEProvincia[] = [
  { id:   1, nombre: "DISTRITO NACIONAL" },
  { id:   2, nombre: "LA ALTAGRACIA" },
  { id:   3, nombre: "AZUA" },
  { id:   4, nombre: "BAHORUCO" },
  { id:   5, nombre: "BARAHONA" },
  { id:   6, nombre: "DAJABON" },
  { id:   7, nombre: "DUARTE" },
  { id:   8, nombre: "EL SEIBO" },
  { id:   9, nombre: "ELIAS PIÑA" },
  { id:  10, nombre: "ESPAILLAT" },
  { id:  11, nombre: "HATO MAYOR" },
  { id:  12, nombre: "INDEPENDENCIA" },
  { id:  13, nombre: "LA ROMANA" },
  { id:  14, nombre: "LA VEGA" },
  { id:  15, nombre: "MARIA TRINIDAD SANCHEZ" },
  { id:  16, nombre: "MONSEÑOR NOUEL" },
  { id:  17, nombre: "MONTE CRISTI" },
  { id:  18, nombre: "MONTE PLATA" },
  { id:  19, nombre: "PEDERNALES" },
  { id:  20, nombre: "PERAVIA" },
  { id:  21, nombre: "PUERTO PLATA" },
  { id:  22, nombre: "HERMANAS MIRABAL" },
  { id:  23, nombre: "SAMANA" },
  { id:  24, nombre: "SAN CRISTOBAL" },
  { id:  25, nombre: "SAN JUAN" },
  { id:  26, nombre: "SAN PEDRO DE MACORIS" },
  { id:  27, nombre: "SANCHEZ RAMIREZ" },
  { id:  28, nombre: "SANTIAGO" },
  { id:  29, nombre: "SANTIAGO RODRIGUEZ" },
  { id:  30, nombre: "VALVERDE" },
  { id:  31, nombre: "SAN JOSE DE OCOA" },
  { id:  32, nombre: "SANTO DOMINGO" },
]

export const JCE_MUNICIPIOS: JCEMunicipio[] = [
  { id:   1, idProvincia:  1, nombre: "DISTRITO NACIONAL" },
  { id:  28, idProvincia:  2, nombre: "HIGUEY" },
  { id:  85, idProvincia:  2, nombre: "SAN RAFAEL DEL YUMA" },
  { id:  10, idProvincia:  3, nombre: "AZUA" },
  { id:  17, idProvincia:  3, nombre: "PADRE LAS CASAS" },
  { id: 105, idProvincia:  3, nombre: "GUAYABAL" },
  { id: 106, idProvincia:  3, nombre: "PERALTA" },
  { id: 107, idProvincia:  3, nombre: "SABANA YEGUA" },
  { id: 125, idProvincia:  3, nombre: "LAS YAYAS DE VIAJAMA" },
  { id: 126, idProvincia:  3, nombre: "TABARA ARRIBA" },
  { id: 132, idProvincia:  3, nombre: "ESTEBANIA" },
  { id: 135, idProvincia:  3, nombre: "LAS CHARCAS" },
  { id: 154, idProvincia:  3, nombre: "PUEBLO VIEJO" },
  { id:  22, idProvincia:  4, nombre: "NEYBA" },
  { id:  76, idProvincia:  4, nombre: "TAMAYO" },
  { id:  78, idProvincia:  4, nombre: "VILLA JARAGUA" },
  { id: 112, idProvincia:  4, nombre: "LOS RIOS" },
  { id: 113, idProvincia:  4, nombre: "GALVAN" },
  { id:  18, idProvincia:  5, nombre: "BARAHONA" },
  { id:  19, idProvincia:  5, nombre: "CABRAL" },
  { id:  21, idProvincia:  5, nombre: "ENRIQUILLO" },
  { id:  79, idProvincia:  5, nombre: "VICENTE NOBLE" },
  { id:  80, idProvincia:  5, nombre: "PARAISO" },
  { id: 111, idProvincia:  5, nombre: "POLO" },
  { id: 130, idProvincia:  5, nombre: "EL PEÑON" },
  { id: 131, idProvincia:  5, nombre: "FUNDACION" },
  { id: 137, idProvincia:  5, nombre: "LAS SALINAS" },
  { id: 160, idProvincia:  5, nombre: "LA CIENAGA" },
  { id: 167, idProvincia:  5, nombre: "JAQUIMEYES" },
  { id:  43, idProvincia:  6, nombre: "RESTAURACION" },
  { id:  44, idProvincia:  6, nombre: "DAJABON" },
  { id:  73, idProvincia:  6, nombre: "LOMA DE CABRERA" },
  { id: 115, idProvincia:  6, nombre: "PARTIDO" },
  { id: 151, idProvincia:  6, nombre: "EL PINO" },
  { id:  56, idProvincia:  7, nombre: "SAN FRANCISCO DE MACORIS" },
  { id:  57, idProvincia:  7, nombre: "PIMENTEL" },
  { id:  58, idProvincia:  7, nombre: "VILLA RIVA" },
  { id:  59, idProvincia:  7, nombre: "CASTILLO" },
  { id:  63, idProvincia:  7, nombre: "EUGENIO MARIA DE HOSTOS" },
  { id: 119, idProvincia:  7, nombre: "ARENOSO" },
  { id: 143, idProvincia:  7, nombre: "LAS GUARANAS" },
  { id:  25, idProvincia:  8, nombre: "EL SEIBO" },
  { id:  29, idProvincia:  8, nombre: "MICHES" },
  { id:  15, idProvincia:  9, nombre: "BANICA" },
  { id:  16, idProvincia:  9, nombre: "COMENDADOR" },
  { id:  74, idProvincia:  9, nombre: "PEDRO SANTANA" },
  { id:  75, idProvincia:  9, nombre: "HONDO VALLE" },
  { id: 110, idProvincia:  9, nombre: "EL LLANO" },
  { id: 144, idProvincia:  9, nombre: "JUAN SANTIAGO" },
  { id:  54, idProvincia: 10, nombre: "MOCA" },
  { id:  61, idProvincia: 10, nombre: "GASPAR HERNANDEZ" },
  { id:  88, idProvincia: 10, nombre: "CAYETANO GERMOSEN" },
  { id: 133, idProvincia: 10, nombre: "JAMAO AL NORTE" },
  { id: 149, idProvincia: 10, nombre: "SAN VICTOR" },
  { id:  27, idProvincia: 11, nombre: "HATO MAYOR" },
  { id:  67, idProvincia: 11, nombre: "SABANA DE LA MAR" },
  { id: 100, idProvincia: 11, nombre: "EL VALLE" },
  { id:  20, idProvincia: 12, nombre: "DUVERGE" },
  { id:  70, idProvincia: 12, nombre: "LA DESCUBIERTA" },
  { id:  77, idProvincia: 12, nombre: "JIMANI" },
  { id:  99, idProvincia: 12, nombre: "POSTRER RIO" },
  { id: 114, idProvincia: 12, nombre: "MELLA" },
  { id: 128, idProvincia: 12, nombre: "CRISTOBAL" },
  { id:  26, idProvincia: 13, nombre: "LA ROMANA" },
  { id: 103, idProvincia: 13, nombre: "GUAYMATE" },
  { id: 295, idProvincia: 13, nombre: "VILLA HERMOSA" },
  { id:  47, idProvincia: 14, nombre: "LA VEGA" },
  { id:  50, idProvincia: 14, nombre: "JARABACOA" },
  { id:  53, idProvincia: 14, nombre: "CONSTANZA" },
  { id: 122, idProvincia: 14, nombre: "JIMA ABAJO" },
  { id:  60, idProvincia: 15, nombre: "CABRERA" },
  { id:  71, idProvincia: 15, nombre: "NAGUA" },
  { id:  81, idProvincia: 15, nombre: "RIO SAN JUAN" },
  { id: 136, idProvincia: 15, nombre: "EL FACTOR" },
  { id:  48, idProvincia: 16, nombre: "BONAO" },
  { id: 118, idProvincia: 16, nombre: "MAIMON" },
  { id: 123, idProvincia: 16, nombre: "PIEDRA BLANCA" },
  { id:  41, idProvincia: 17, nombre: "MONTECRISTI" },
  { id:  45, idProvincia: 17, nombre: "GUAYUBIN" },
  { id:  72, idProvincia: 17, nombre: "VILLA VASQUEZ" },
  { id:  86, idProvincia: 17, nombre: "PEPILLO SALCEDO" },
  { id: 101, idProvincia: 17, nombre: "CASTAÑUELAS" },
  { id: 117, idProvincia: 17, nombre: "LAS MATAS DE SANTA CRUZ" },
  { id:   4, idProvincia: 18, nombre: "BAYAGUANA" },
  { id:   5, idProvincia: 18, nombre: "YAMASA" },
  { id:   8, idProvincia: 18, nombre: "MONTE PLATA" },
  { id:  90, idProvincia: 18, nombre: "SABANA GRANDE DE BOYA" },
  { id: 153, idProvincia: 18, nombre: "PERALVILLO" },
  { id:  69, idProvincia: 19, nombre: "PEDERNALES" },
  { id:  91, idProvincia: 19, nombre: "OVIEDO" },
  { id:   3, idProvincia: 20, nombre: "BANI" },
  { id:  84, idProvincia: 20, nombre: "NIZAO" },
  { id: 156, idProvincia: 20, nombre: "MATANZAS" },
  { id:  37, idProvincia: 21, nombre: "PUERTO PLATA" },
  { id:  38, idProvincia: 21, nombre: "IMBERT" },
  { id:  39, idProvincia: 21, nombre: "ALTAMIRA" },
  { id:  40, idProvincia: 21, nombre: "LUPERON" },
  { id:  97, idProvincia: 21, nombre: "SOSUA" },
  { id: 102, idProvincia: 21, nombre: "LOS HIDALGOS" },
  { id: 120, idProvincia: 21, nombre: "GUANANICO" },
  { id: 121, idProvincia: 21, nombre: "VILLA ISABELA" },
  { id: 175, idProvincia: 21, nombre: "VILLA MONTELLANO" },
  { id:  51, idProvincia: 22, nombre: "VILLA TAPIA" },
  { id:  55, idProvincia: 22, nombre: "SALCEDO" },
  { id:  64, idProvincia: 22, nombre: "TENARES" },
  { id:  65, idProvincia: 23, nombre: "SAMANA" },
  { id:  66, idProvincia: 23, nombre: "SANCHEZ" },
  { id: 134, idProvincia: 23, nombre: "LAS TERRENAS" },
  { id:   2, idProvincia: 24, nombre: "SAN CRISTOBAL" },
  { id:  68, idProvincia: 24, nombre: "VILLA ALTAGRACIA" },
  { id:  82, idProvincia: 24, nombre: "YAGUATE" },
  { id:  83, idProvincia: 24, nombre: "SABANA GRANDE DE PALENQUE" },
  { id:  93, idProvincia: 24, nombre: "BAJOS DE HAINA" },
  { id: 104, idProvincia: 24, nombre: "CAMBITA GARABITOS" },
  { id: 139, idProvincia: 24, nombre: "LOS CACAOS" },
  { id: 140, idProvincia: 24, nombre: "SAN GREGORIO DE NIGUA" },
  { id:  11, idProvincia: 25, nombre: "LAS MATAS DE FARFAN" },
  { id:  12, idProvincia: 25, nombre: "SAN JUAN DE LA MAGUANA" },
  { id:  14, idProvincia: 25, nombre: "EL CERCADO" },
  { id: 108, idProvincia: 25, nombre: "VALLEJUELO" },
  { id: 109, idProvincia: 25, nombre: "BOHECHIO" },
  { id: 129, idProvincia: 25, nombre: "JUAN DE HERRERA" },
  { id:  23, idProvincia: 26, nombre: "SAN PEDRO DE MACORIS" },
  { id:  24, idProvincia: 26, nombre: "LOS LLANOS" },
  { id:  30, idProvincia: 26, nombre: "RAMON SANTANA" },
  { id: 138, idProvincia: 26, nombre: "CONSUELO" },
  { id: 146, idProvincia: 26, nombre: "QUISQUEYA" },
  { id: 364, idProvincia: 26, nombre: "GUAYACANES" },
  { id:  49, idProvincia: 27, nombre: "COTUI" },
  { id:  52, idProvincia: 27, nombre: "CEVICOS" },
  { id:  87, idProvincia: 27, nombre: "FANTINO" },
  { id: 155, idProvincia: 27, nombre: "VILLA LA MATA" },
  { id:  31, idProvincia: 28, nombre: "SANTIAGO DE LOS CABALLEROS" },
  { id:  32, idProvincia: 28, nombre: "TAMBORIL" },
  { id:  35, idProvincia: 28, nombre: "JANICO" },
  { id:  36, idProvincia: 28, nombre: "SAN JOSE DE LAS MATAS" },
  { id:  94, idProvincia: 28, nombre: "VILLA GONZALEZ" },
  { id:  95, idProvincia: 28, nombre: "LICEY AL MEDIO" },
  { id:  96, idProvincia: 28, nombre: "VILLA BISONO -NAVARRETE-" },
  { id: 148, idProvincia: 28, nombre: "SABANA IGLESIA" },
  { id: 161, idProvincia: 28, nombre: "BAITOA" },
  { id: 350, idProvincia: 28, nombre: "PUÑAL" },
  { id:  42, idProvincia: 29, nombre: "MONCION" },
  { id:  46, idProvincia: 29, nombre: "SAN IGNACIO DE SABANETA" },
  { id: 116, idProvincia: 29, nombre: "VILLA LOS ALMACIGOS" },
  { id:  33, idProvincia: 30, nombre: "ESPERANZA" },
  { id:  34, idProvincia: 30, nombre: "MAO" },
  { id:  92, idProvincia: 30, nombre: "LAGUNA SALADA" },
  { id:  13, idProvincia: 31, nombre: "SAN JOSE DE OCOA" },
  { id: 150, idProvincia: 31, nombre: "SABANA LARGA" },
  { id: 152, idProvincia: 31, nombre: "RANCHO ARRIBA" },
  { id: 223, idProvincia: 32, nombre: "SANTO DOMINGO ESTE" },
  { id: 224, idProvincia: 32, nombre: "SANTO DOMINGO OESTE" },
  { id: 225, idProvincia: 32, nombre: "SANTO DOMINGO NORTE" },
  { id: 226, idProvincia: 32, nombre: "BOCA CHICA" },
  { id: 227, idProvincia: 32, nombre: "SAN ANTONIO DE GUERRA" },
  { id: 228, idProvincia: 32, nombre: "PEDRO BRAND" },
  { id: 229, idProvincia: 32, nombre: "LOS ALCARRIZOS" },
]

export const JCE_DISTRITOS_MUNICIPALES: JCEDistritoMunicipal[] = [
  { id: 141, idProvincia:  2, idMunicipioPadre:  28, nombre: "LA LAGUNA DE NISIBON" },
  { id: 145, idProvincia:  2, idMunicipioPadre:  28, nombre: "LA OTRA BANDA" },
  { id: 385, idProvincia:  2, idMunicipioPadre:  28, nombre: "TURISTICO VERON PUNTA CANA" },
  { id: 211, idProvincia:  2, idMunicipioPadre:  85, nombre: "BOCA DE YUMA" },
  { id: 249, idProvincia:  2, idMunicipioPadre:  85, nombre: "BAYAHIBE" },
  { id: 264, idProvincia:  3, idMunicipioPadre:  10, nombre: "LAS BARIAS-LA ESTANCIA" },
  { id: 267, idProvincia:  3, idMunicipioPadre:  10, nombre: "LOS JOVILLOS" },
  { id: 276, idProvincia:  3, idMunicipioPadre:  10, nombre: "BARRO ARRIBA" },
  { id: 334, idProvincia:  3, idMunicipioPadre:  10, nombre: "PUERTO VIEJO-LOS NEGROS" },
  { id: 335, idProvincia:  3, idMunicipioPadre:  10, nombre: "BARRERAS" },
  { id: 340, idProvincia:  3, idMunicipioPadre:  10, nombre: "DOÑA EMMA BALAGUER VDA. VALLEJO" },
  { id: 341, idProvincia:  3, idMunicipioPadre:  10, nombre: "LAS CLAVELLINAS" },
  { id: 355, idProvincia:  3, idMunicipioPadre:  10, nombre: "LAS LOMAS" },
  { id: 303, idProvincia:  3, idMunicipioPadre:  17, nombre: "LAS LAGUNAS" },
  { id: 304, idProvincia:  3, idMunicipioPadre:  17, nombre: "LA SIEMBRA" },
  { id: 339, idProvincia:  3, idMunicipioPadre:  17, nombre: "MONTE BONITO" },
  { id: 370, idProvincia:  3, idMunicipioPadre:  17, nombre: "LOS FRIOS" },
  { id: 259, idProvincia:  3, idMunicipioPadre: 107, nombre: "PROYECTO #4" },
  { id: 260, idProvincia:  3, idMunicipioPadre: 107, nombre: "PROYECTO D-1 GANADERO" },
  { id: 380, idProvincia:  3, idMunicipioPadre: 107, nombre: "PROYECTO 2-C" },
  { id: 231, idProvincia:  3, idMunicipioPadre: 125, nombre: "VILLARPANDO" },
  { id: 377, idProvincia:  3, idMunicipioPadre: 125, nombre: "HATO NUEVO CORTES" },
  { id: 257, idProvincia:  3, idMunicipioPadre: 126, nombre: "LOS TOROS" },
  { id: 282, idProvincia:  3, idMunicipioPadre: 126, nombre: "AMIAMA GOMEZ" },
  { id: 283, idProvincia:  3, idMunicipioPadre: 126, nombre: "TABARA ABAJO" },
  { id: 207, idProvincia:  3, idMunicipioPadre: 135, nombre: "PALMAR DE OCOA" },
  { id: 261, idProvincia:  3, idMunicipioPadre: 154, nombre: "EL ROSARIO" },
  { id: 214, idProvincia:  4, idMunicipioPadre:  22, nombre: "EL PALMAR" },
  { id: 127, idProvincia:  4, idMunicipioPadre:  76, nombre: "UVILLA" },
  { id: 289, idProvincia:  4, idMunicipioPadre:  76, nombre: "SANTANA" },
  { id: 298, idProvincia:  4, idMunicipioPadre:  76, nombre: "MONSERRAT" },
  { id: 333, idProvincia:  4, idMunicipioPadre:  76, nombre: "CABEZA DE TORO" },
  { id: 371, idProvincia:  4, idMunicipioPadre:  76, nombre: "MENA" },
  { id: 386, idProvincia:  4, idMunicipioPadre:  76, nombre: "SANTA BARBARA EL 6" },
  { id: 288, idProvincia:  4, idMunicipioPadre: 112, nombre: "LAS CLAVELLINAS" },
  { id: 387, idProvincia:  4, idMunicipioPadre: 113, nombre: "EL SALADO" },
  { id: 198, idProvincia:  5, idMunicipioPadre:  18, nombre: "EL CACHON" },
  { id: 356, idProvincia:  5, idMunicipioPadre:  18, nombre: "LA GUAZARA" },
  { id: 389, idProvincia:  5, idMunicipioPadre:  18, nombre: "VILLA CENTRAL" },
  { id: 284, idProvincia:  5, idMunicipioPadre:  21, nombre: "ARROYO DULCE" },
  { id: 164, idProvincia:  5, idMunicipioPadre:  79, nombre: "CANOA" },
  { id: 272, idProvincia:  5, idMunicipioPadre:  79, nombre: "QUITA CORAZA" },
  { id: 279, idProvincia:  5, idMunicipioPadre:  79, nombre: "FONDO NEGRO" },
  { id: 222, idProvincia:  5, idMunicipioPadre:  80, nombre: "LOS PATOS" },
  { id: 216, idProvincia:  5, idMunicipioPadre: 131, nombre: "PESCADERIA" },
  { id: 301, idProvincia:  5, idMunicipioPadre: 160, nombre: "BAHORUCO" },
  { id: 294, idProvincia:  5, idMunicipioPadre: 167, nombre: "PALO ALTO" },
  { id: 321, idProvincia:  6, idMunicipioPadre:  44, nombre: "CAÑONGO" },
  { id: 318, idProvincia:  6, idMunicipioPadre:  73, nombre: "CAPOTILLO" },
  { id: 365, idProvincia:  6, idMunicipioPadre:  73, nombre: "SANTIAGO DE LA CRUZ" },
  { id: 242, idProvincia:  6, idMunicipioPadre: 151, nombre: "MANUEL BUENO" },
  { id: 189, idProvincia:  7, idMunicipioPadre:  56, nombre: "LA PEÑA" },
  { id: 205, idProvincia:  7, idMunicipioPadre:  56, nombre: "CENOVI" },
  { id: 363, idProvincia:  7, idMunicipioPadre:  56, nombre: "JAYA" },
  { id: 376, idProvincia:  7, idMunicipioPadre:  56, nombre: "DON ANTONIO GUZMAN FERNANDEZ" },
  { id: 182, idProvincia:  7, idMunicipioPadre:  58, nombre: "AGUA SANTA DEL YUNA" },
  { id: 183, idProvincia:  7, idMunicipioPadre:  58, nombre: "CRISTO REY DE GUARAGUAO" },
  { id: 265, idProvincia:  7, idMunicipioPadre:  58, nombre: "LAS TARANAS" },
  { id: 345, idProvincia:  7, idMunicipioPadre:  58, nombre: "BARRAQUITO" },
  { id: 290, idProvincia:  7, idMunicipioPadre:  63, nombre: "SABANA GRANDE" },
  { id: 266, idProvincia:  7, idMunicipioPadre: 119, nombre: "LAS COLES" },
  { id: 344, idProvincia:  7, idMunicipioPadre: 119, nombre: "EL AGUACATE" },
  { id: 166, idProvincia:  8, idMunicipioPadre:  25, nombre: "PEDRO SANCHEZ" },
  { id: 367, idProvincia:  8, idMunicipioPadre:  25, nombre: "SAN FRANCISCO-VICENTILLO" },
  { id: 378, idProvincia:  8, idMunicipioPadre:  25, nombre: "SANTA LUCIA-LA HIGUERA" },
  { id: 237, idProvincia:  8, idMunicipioPadre:  29, nombre: "EL JOVERO" },
  { id: 324, idProvincia:  8, idMunicipioPadre:  29, nombre: "LA GINA" },
  { id: 338, idProvincia:  9, idMunicipioPadre:  15, nombre: "SABANA CRUZ" },
  { id: 361, idProvincia:  9, idMunicipioPadre:  15, nombre: "SABANA HIGUERO" },
  { id: 280, idProvincia:  9, idMunicipioPadre:  16, nombre: "SABANA LARGA" },
  { id: 359, idProvincia:  9, idMunicipioPadre:  16, nombre: "GUAYABO" },
  { id: 159, idProvincia:  9, idMunicipioPadre:  74, nombre: "RIO LIMPIO" },
  { id: 368, idProvincia:  9, idMunicipioPadre:  75, nombre: "RANCHO DE LA GUARDIA" },
  { id: 337, idProvincia:  9, idMunicipioPadre: 110, nombre: "GUANITO" },
  { id:  89, idProvincia: 10, idMunicipioPadre:  54, nombre: "JOSE CONTRERAS" },
  { id: 208, idProvincia: 10, idMunicipioPadre:  54, nombre: "JUAN LOPEZ ABAJO" },
  { id: 236, idProvincia: 10, idMunicipioPadre:  54, nombre: "LAS LAGUNAS ABAJO" },
  { id: 273, idProvincia: 10, idMunicipioPadre:  54, nombre: "HIGUERITO" },
  { id: 274, idProvincia: 10, idMunicipioPadre:  54, nombre: "MONTE DE LA JAGUA" },
  { id: 275, idProvincia: 10, idMunicipioPadre:  54, nombre: "ORTEGA" },
  { id: 285, idProvincia: 10, idMunicipioPadre:  54, nombre: "CANCA LA REYNA" },
  { id: 162, idProvincia: 10, idMunicipioPadre:  61, nombre: "JOBA ARRIBA" },
  { id: 240, idProvincia: 10, idMunicipioPadre:  61, nombre: "VERAGUA" },
  { id: 342, idProvincia: 10, idMunicipioPadre:  61, nombre: "VILLA MAGANTE" },
  { id: 168, idProvincia: 11, idMunicipioPadre:  27, nombre: "YERBA BUENA" },
  { id: 202, idProvincia: 11, idMunicipioPadre:  27, nombre: "MATA PALACIO" },
  { id: 215, idProvincia: 11, idMunicipioPadre:  27, nombre: "GUAYABO DULCE" },
  { id: 169, idProvincia: 11, idMunicipioPadre:  67, nombre: "ELUPINA CORDERO DE LAS CAÑITAS" },
  { id: 323, idProvincia: 12, idMunicipioPadre:  20, nombre: "VENGAN A VER" },
  { id: 238, idProvincia: 12, idMunicipioPadre:  77, nombre: "EL LIMON" },
  { id: 316, idProvincia: 12, idMunicipioPadre:  77, nombre: "BOCA DE CACHON" },
  { id: 178, idProvincia: 12, idMunicipioPadre:  99, nombre: "GUAYABAL" },
  { id: 293, idProvincia: 12, idMunicipioPadre: 114, nombre: "LA COLONIA" },
  { id: 379, idProvincia: 12, idMunicipioPadre: 128, nombre: "BATEY 8" },
  { id: 360, idProvincia: 13, idMunicipioPadre:  26, nombre: "LA CALETA" },
  { id: 296, idProvincia: 13, idMunicipioPadre: 295, nombre: "CUMAYASA" },
  { id: 181, idProvincia: 14, idMunicipioPadre:  47, nombre: "RIO VERDE ARRIBA" },
  { id: 251, idProvincia: 14, idMunicipioPadre:  47, nombre: "EL RANCHITO" },
  { id: 392, idProvincia: 14, idMunicipioPadre:  47, nombre: "TAVERA" },
  { id: 394, idProvincia: 14, idMunicipioPadre:  47, nombre: "DON JUAN RODRIGUEZ - BARRANCA" },
  { id: 300, idProvincia: 14, idMunicipioPadre:  50, nombre: "BUENA VISTA" },
  { id: 349, idProvincia: 14, idMunicipioPadre:  50, nombre: "MANABAO" },
  { id: 163, idProvincia: 14, idMunicipioPadre:  53, nombre: "TIREO ARRIBA" },
  { id: 250, idProvincia: 14, idMunicipioPadre:  53, nombre: "LA SABINA" },
  { id: 187, idProvincia: 14, idMunicipioPadre: 122, nombre: "RINCON" },
  { id: 203, idProvincia: 15, idMunicipioPadre:  60, nombre: "ARROYO SALADO" },
  { id: 212, idProvincia: 15, idMunicipioPadre:  60, nombre: "LA ENTRADA" },
  { id: 165, idProvincia: 15, idMunicipioPadre:  71, nombre: "SAN JOSE DE MATANZAS" },
  { id: 271, idProvincia: 15, idMunicipioPadre:  71, nombre: "LAS GORDAS" },
  { id: 347, idProvincia: 15, idMunicipioPadre:  71, nombre: "ARROYO AL MEDIO" },
  { id: 213, idProvincia: 15, idMunicipioPadre: 136, nombre: "EL POZO" },
  { id: 201, idProvincia: 16, idMunicipioPadre:  48, nombre: "SABANA DEL PUERTO" },
  { id: 281, idProvincia: 16, idMunicipioPadre:  48, nombre: "JUMA BEJUCAL" },
  { id: 354, idProvincia: 16, idMunicipioPadre:  48, nombre: "ARROYO TORO-MASIPEDRO" },
  { id: 362, idProvincia: 16, idMunicipioPadre:  48, nombre: "JAYACO" },
  { id: 383, idProvincia: 16, idMunicipioPadre:  48, nombre: "LA SALVIA-LOS QUEMADOS" },
  { id: 199, idProvincia: 16, idMunicipioPadre: 123, nombre: "VILLA SONADOR" },
  { id: 210, idProvincia: 16, idMunicipioPadre: 123, nombre: "JUAN ADRIAN" },
  { id: 171, idProvincia: 17, idMunicipioPadre:  45, nombre: "VILLA ELISA" },
  { id: 173, idProvincia: 17, idMunicipioPadre:  45, nombre: "HATILLO PALMA" },
  { id: 241, idProvincia: 17, idMunicipioPadre:  45, nombre: "CANA CHAPETON" },
  { id: 395, idProvincia: 17, idMunicipioPadre:  86, nombre: "SANTA MARIA" },
  { id: 253, idProvincia: 17, idMunicipioPadre: 101, nombre: "PALO VERDE" },
  { id: 179, idProvincia: 18, idMunicipioPadre:   5, nombre: "LOS BOTADOS" },
  { id: 391, idProvincia: 18, idMunicipioPadre:   5, nombre: "MAMA TINGO" },
  { id: 147, idProvincia: 18, idMunicipioPadre:   8, nombre: "DON JUAN" },
  { id: 254, idProvincia: 18, idMunicipioPadre:   8, nombre: "CHIRINO" },
  { id: 299, idProvincia: 18, idMunicipioPadre:   8, nombre: "BOYA-EL CENTRO" },
  { id: 174, idProvincia: 18, idMunicipioPadre:  90, nombre: "GONZALO" },
  { id: 209, idProvincia: 18, idMunicipioPadre:  90, nombre: "MAJAGUAL" },
  { id: 325, idProvincia: 19, idMunicipioPadre:  69, nombre: "JOSE FRANCISCO PEÑA GOMEZ" },
  { id: 184, idProvincia: 19, idMunicipioPadre:  91, nombre: "JUANCHO" },
  { id: 157, idProvincia: 20, idMunicipioPadre:   3, nombre: "VILLA FUNDACION" },
  { id: 158, idProvincia: 20, idMunicipioPadre:   3, nombre: "SABANA BUEY" },
  { id: 185, idProvincia: 20, idMunicipioPadre:   3, nombre: "PAYA" },
  { id: 221, idProvincia: 20, idMunicipioPadre:   3, nombre: "VILLA SOMBRERO" },
  { id: 235, idProvincia: 20, idMunicipioPadre:   3, nombre: "EL CARRETON" },
  { id: 302, idProvincia: 20, idMunicipioPadre:   3, nombre: "LA CATALINA" },
  { id: 358, idProvincia: 20, idMunicipioPadre:   3, nombre: "EL LIMONAL" },
  { id: 381, idProvincia: 20, idMunicipioPadre:   3, nombre: "LAS BARIAS" },
  { id: 170, idProvincia: 20, idMunicipioPadre:  84, nombre: "PIZARRETE" },
  { id: 176, idProvincia: 20, idMunicipioPadre:  84, nombre: "SANTANA" },
  { id: 332, idProvincia: 21, idMunicipioPadre:  37, nombre: "YASICA ARRIBA" },
  { id: 372, idProvincia: 21, idMunicipioPadre:  37, nombre: "MAIMON" },
  { id: 346, idProvincia: 21, idMunicipioPadre:  39, nombre: "RIO GRANDE" },
  { id: 188, idProvincia: 21, idMunicipioPadre:  40, nombre: "LA ISABELA" },
  { id: 243, idProvincia: 21, idMunicipioPadre:  40, nombre: "BELLOSO" },
  { id: 375, idProvincia: 21, idMunicipioPadre:  40, nombre: "ESTRECHO DE LUPERON OMAR BROSS" },
  { id: 244, idProvincia: 21, idMunicipioPadre:  97, nombre: "CABARETE" },
  { id: 245, idProvincia: 21, idMunicipioPadre:  97, nombre: "SABANETA DE YASICA" },
  { id: 305, idProvincia: 21, idMunicipioPadre: 102, nombre: "NAVAS" },
  { id: 177, idProvincia: 21, idMunicipioPadre: 121, nombre: "ESTERO HONDO" },
  { id: 263, idProvincia: 21, idMunicipioPadre: 121, nombre: "LA JAIBA" },
  { id: 388, idProvincia: 21, idMunicipioPadre: 121, nombre: "GUALETE" },
  { id: 270, idProvincia: 22, idMunicipioPadre:  55, nombre: "MONTE LLANO" },
  { id: 193, idProvincia: 22, idMunicipioPadre:  64, nombre: "BLANCO" },
  { id: 218, idProvincia: 23, idMunicipioPadre:  65, nombre: "EL LIMON" },
  { id: 262, idProvincia: 23, idMunicipioPadre:  65, nombre: "ARROYO BARRIL" },
  { id: 322, idProvincia: 23, idMunicipioPadre:  65, nombre: "LAS GALERAS" },
  { id: 306, idProvincia: 24, idMunicipioPadre:   2, nombre: "HATO DAMAS" },
  { id: 397, idProvincia: 24, idMunicipioPadre:   2, nombre: "HATILLO" },
  { id: 252, idProvincia: 24, idMunicipioPadre:  68, nombre: "SAN JOSE-PINO HERRADO-EL PUERTO" },
  { id: 255, idProvincia: 24, idMunicipioPadre:  68, nombre: "MEDINA" },
  { id: 256, idProvincia: 24, idMunicipioPadre:  68, nombre: "LA CUCHILLA" },
  { id: 396, idProvincia: 24, idMunicipioPadre:  82, nombre: "DOÑA ANA" },
  { id: 234, idProvincia: 24, idMunicipioPadre:  93, nombre: "EL CARRIL" },
  { id: 398, idProvincia: 24, idMunicipioPadre:  93, nombre: "QUITA SUEÑO" },
  { id: 315, idProvincia: 24, idMunicipioPadre: 104, nombre: "CAMBITA EL PUEBLECITO" },
  { id: 186, idProvincia: 25, idMunicipioPadre:  11, nombre: "MATAYAYA" },
  { id: 330, idProvincia: 25, idMunicipioPadre:  11, nombre: "CARRERA DE YEGUAS" },
  { id: 190, idProvincia: 25, idMunicipioPadre:  12, nombre: "PEDRO CORTO" },
  { id: 292, idProvincia: 25, idMunicipioPadre:  12, nombre: "SABANETA" },
  { id: 314, idProvincia: 25, idMunicipioPadre:  12, nombre: "SABANA ALTA" },
  { id: 319, idProvincia: 25, idMunicipioPadre:  12, nombre: "EL ROSARIO" },
  { id: 326, idProvincia: 25, idMunicipioPadre:  12, nombre: "HATO DEL PADRE" },
  { id: 331, idProvincia: 25, idMunicipioPadre:  12, nombre: "GUANITO" },
  { id: 336, idProvincia: 25, idMunicipioPadre:  12, nombre: "LA JAGUA" },
  { id: 353, idProvincia: 25, idMunicipioPadre:  12, nombre: "LAS MAGUANAS-HATO NUEVO" },
  { id: 357, idProvincia: 25, idMunicipioPadre:  12, nombre: "LAS CHARCAS DE MARIA NOVAS" },
  { id: 390, idProvincia: 25, idMunicipioPadre:  12, nombre: "LA ZANJA" },
  { id: 317, idProvincia: 25, idMunicipioPadre:  14, nombre: "DERRUMBADERO" },
  { id: 329, idProvincia: 25, idMunicipioPadre:  14, nombre: "BATISTA" },
  { id: 348, idProvincia: 25, idMunicipioPadre: 108, nombre: "JORGILLO" },
  { id: 287, idProvincia: 25, idMunicipioPadre: 109, nombre: "ARROYO CANO" },
  { id: 297, idProvincia: 25, idMunicipioPadre: 109, nombre: "YAQUE" },
  { id: 366, idProvincia: 25, idMunicipioPadre: 129, nombre: "JINOVA" },
  { id: 200, idProvincia: 26, idMunicipioPadre:  24, nombre: "EL PUERTO" },
  { id: 247, idProvincia: 26, idMunicipioPadre:  24, nombre: "GAUTIER" },
  { id: 309, idProvincia: 27, idMunicipioPadre:  49, nombre: "PLATANAL" },
  { id: 320, idProvincia: 27, idMunicipioPadre:  49, nombre: "QUITA SUEÑO" },
  { id: 369, idProvincia: 27, idMunicipioPadre:  49, nombre: "CABALLERO" },
  { id: 373, idProvincia: 27, idMunicipioPadre:  49, nombre: "COMEDERO ARRIBA" },
  { id: 393, idProvincia: 27, idMunicipioPadre:  49, nombre: "ZAMBRANA ABAJO" },
  { id: 124, idProvincia: 27, idMunicipioPadre:  52, nombre: "LA CUEVA" },
  { id: 220, idProvincia: 27, idMunicipioPadre: 155, nombre: "LA BIJA" },
  { id: 233, idProvincia: 27, idMunicipioPadre: 155, nombre: "ANGELINA" },
  { id: 384, idProvincia: 27, idMunicipioPadre: 155, nombre: "HERNANDO ALONZO" },
  { id: 142, idProvincia: 28, idMunicipioPadre:  31, nombre: "PEDRO GARCIA" },
  { id: 172, idProvincia: 28, idMunicipioPadre:  31, nombre: "LA CANELA" },
  { id: 239, idProvincia: 28, idMunicipioPadre:  31, nombre: "SAN FRANCISCO DE JACAGUA" },
  { id: 258, idProvincia: 28, idMunicipioPadre:  31, nombre: "HATO DEL YAQUE" },
  { id: 399, idProvincia: 28, idMunicipioPadre:  31, nombre: "SANTIAGO OESTE-CIENFUEGOS" },
  { id: 374, idProvincia: 28, idMunicipioPadre:  32, nombre: "CANCA LA PIEDRA" },
  { id: 192, idProvincia: 28, idMunicipioPadre:  35, nombre: "JUNCALITO" },
  { id: 308, idProvincia: 28, idMunicipioPadre:  35, nombre: "EL CAIMITO" },
  { id: 191, idProvincia: 28, idMunicipioPadre:  36, nombre: "EL RUBIO" },
  { id: 268, idProvincia: 28, idMunicipioPadre:  36, nombre: "LAS CUESTA" },
  { id: 269, idProvincia: 28, idMunicipioPadre:  36, nombre: "LAS PLACETAS" },
  { id: 219, idProvincia: 28, idMunicipioPadre:  94, nombre: "PALMAR ARRIBA" },
  { id: 246, idProvincia: 28, idMunicipioPadre:  94, nombre: "EL LIMON" },
  { id: 327, idProvincia: 28, idMunicipioPadre:  95, nombre: "LAS PALOMAS" },
  { id: 351, idProvincia: 28, idMunicipioPadre: 350, nombre: "GUAYABAL" },
  { id: 352, idProvincia: 28, idMunicipioPadre: 350, nombre: "CANABACOA ABAJO" },
  { id: 197, idProvincia: 30, idMunicipioPadre:  33, nombre: "MAIZAL" },
  { id: 204, idProvincia: 30, idMunicipioPadre:  33, nombre: "JICOME" },
  { id: 328, idProvincia: 30, idMunicipioPadre:  33, nombre: "BOCA DE MAO" },
  { id: 343, idProvincia: 30, idMunicipioPadre:  33, nombre: "PARADERO" },
  { id: 194, idProvincia: 30, idMunicipioPadre:  34, nombre: "AMINA" },
  { id: 195, idProvincia: 30, idMunicipioPadre:  34, nombre: "JAIBON" },
  { id: 196, idProvincia: 30, idMunicipioPadre:  34, nombre: "GUATAPANAL" },
  { id: 217, idProvincia: 30, idMunicipioPadre:  92, nombre: "JAIBON" },
  { id: 232, idProvincia: 30, idMunicipioPadre:  92, nombre: "LA CAYA" },
  { id: 248, idProvincia: 30, idMunicipioPadre:  92, nombre: "CRUCE DE GUAYACANES" },
  { id: 180, idProvincia: 31, idMunicipioPadre:  13, nombre: "LA CIENAGA" },
  { id: 277, idProvincia: 31, idMunicipioPadre:  13, nombre: "NIZAO-LAS AUYAMAS" },
  { id: 278, idProvincia: 31, idMunicipioPadre:  13, nombre: "EL PINAR" },
  { id: 382, idProvincia: 31, idMunicipioPadre:  13, nombre: "EL NARANJAL" },
  { id: 291, idProvincia: 32, idMunicipioPadre: 223, nombre: "SAN LUIS" },
  { id: 230, idProvincia: 32, idMunicipioPadre: 225, nombre: "LA VICTORIA" },
  { id: 286, idProvincia: 32, idMunicipioPadre: 226, nombre: "LA CALETA" },
  { id: 307, idProvincia: 32, idMunicipioPadre: 227, nombre: "HATO VIEJO" },
  { id: 310, idProvincia: 32, idMunicipioPadre: 228, nombre: "LA GUAYIGA" },
  { id: 311, idProvincia: 32, idMunicipioPadre: 228, nombre: "LA CUABA" },
  { id: 312, idProvincia: 32, idMunicipioPadre: 229, nombre: "PALMAREJO" },
  { id: 313, idProvincia: 32, idMunicipioPadre: 229, nombre: "PANTOJA" },
]

/** Busca el ID JCE de una provincia por nombre (insensible a mayúsculas/tildes) */
export function findProvinciaId(nombre: string): number | null {
  const n = normalizeJCE(nombre)
  const p = JCE_PROVINCIAS.find(x => normalizeJCE(x.nombre) === n)
  return p?.id ?? null
}

/** Busca el ID JCE de un municipio por nombre y provincia */
export function findMunicipioId(nombre: string, idProvincia: number): number | null {
  const n = normalizeJCE(nombre)
  const m = JCE_MUNICIPIOS.find(x => x.idProvincia === idProvincia && normalizeJCE(x.nombre) === n)
  return m?.id ?? null
}

/** Busca el ID JCE de un DM por nombre y municipio padre */
export function findDistritoMunicipalId(nombre: string, idMunicipioPadre: number): number | null {
  const n = normalizeJCE(nombre)
  const d = JCE_DISTRITOS_MUNICIPALES.find(x =>
    x.idMunicipioPadre === idMunicipioPadre && normalizeJCE(x.nombre) === n
  )
  return d?.id ?? null
}

/** Normaliza un string para comparación flexible (sin tildes, sin (DM), minúsculas) */
function normalizeJCE(s: string): string {
  return s
    .toUpperCase()
    .replace(/\s*\(DM\)\s*/g, '')
    .replace(/[ÁÀÄÂ]/g, 'A')
    .replace(/[ÉÈËÊ]/g, 'E')
    .replace(/[ÍÌÏÎ]/g, 'I')
    .replace(/[ÓÒÖÔ]/g, 'O')
    .replace(/[ÚÙÜÛ]/g, 'U')
    .replace(/Ñ/g, 'N')
    .replace(/[-\s]+/g, ' ')
    .trim()
}
